[variables]
NEXT_PUBLIC_SUPABASE_URL = "https://lnevmejmaqsctopqvkwv.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZXZtZWptYXFzY3RvcHF2a3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NjMzNzEsImV4cCI6MjA5MzEzOTM3MX0.dKZr0vyn6tOtyxc0VwxQD6CtAvtYichLR4c_BKI0Lps"
NEXT_PUBLIC_PLATFORM_URL = "http://178.105.48.97:3000"
