-- ============================================================================
-- QUANTUM NEXUS — Migration: invoices
-- Table: invoices
-- Purpose: Monthly invoices generated by billing-engine.
-- Phase: 1 (Scaffold)
-- Terminal: 4 (Database)
-- ============================================================================

CREATE TABLE invoices (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

  invoice_date          DATE NOT NULL,
  due_date              DATE NOT NULL,
  amount_zmw            DECIMAL(12,2) NOT NULL,
  status                TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'paid', 'grace_period', 'overdue', 'written_off')),
  paid_at               TIMESTAMPTZ,
  lenco_transaction_id  TEXT,

  grace_period_started_at  TIMESTAMPTZ,
  suspension_triggered_at  TIMESTAMPTZ
);

CREATE INDEX idx_invoices_tenant ON invoices(tenant_id);
CREATE INDEX idx_invoices_status ON invoices(status);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "invoices_select" ON invoices
  FOR SELECT USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "invoices_insert" ON invoices
  FOR INSERT WITH CHECK (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "invoices_update" ON invoices
  FOR UPDATE USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "invoices_delete" ON invoices
  FOR DELETE USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

-- PLACEHOLDER: BILLING_ENGINE — Invoice generation and status transition triggers
-- REAL INTEGRATION: /src/lib/db/billing-queries.ts
-- PHASE: 3

-- PLACEHOLDER: LENCO — Payment confirmation webhook trigger
-- REAL INTEGRATION: /src/lib/integrations/lenco.ts
-- PHASE: 3

-- PLACEHOLDER: PAYMENT_TRACKER — Grace period and suspension automation triggers
-- REAL INTEGRATION: /src/lib/db/payment-queries.ts
-- PHASE: 3
