-- ============================================================================
-- QUANTUM NEXUS — Migration: seo_tasks
-- Table: seo_tasks
-- Purpose: Daily SEO tasks generated by seo-domination-engine. Business owner
--          confirms completion of manual tasks.
-- Phase: 1 (Scaffold)
-- Terminal: 4 (Database)
-- ============================================================================

CREATE TABLE seo_tasks (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

  task_date             DATE NOT NULL,
  task_type             TEXT NOT NULL CHECK (task_type IN ('blog_post', 'qa_seed', 'directory_submission', 'content_refresh', 'indexing_request', 'backlink_outreach')),
  status                TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'awaiting_confirmation', 'complete', 'skipped')),

  -- For Q&A tasks
  question_text         TEXT,
  answer_text           TEXT,
  platform              TEXT,
  question_posted_at    TIMESTAMPTZ,
  answer_posted_at      TIMESTAMPTZ,

  -- For blog posts
  content_post_id       UUID REFERENCES content_posts(id),
  target_keyword        TEXT,

  completed_at          TIMESTAMPTZ
);

CREATE INDEX idx_seo_tasks_tenant ON seo_tasks(tenant_id);
CREATE INDEX idx_seo_tasks_date ON seo_tasks(task_date);
CREATE INDEX idx_seo_tasks_status ON seo_tasks(status);

ALTER TABLE seo_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "seo_tasks_select" ON seo_tasks
  FOR SELECT USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "seo_tasks_insert" ON seo_tasks
  FOR INSERT WITH CHECK (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "seo_tasks_update" ON seo_tasks
  FOR UPDATE USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

CREATE POLICY "seo_tasks_delete" ON seo_tasks
  FOR DELETE USING (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

-- PLACEHOLDER: SEO_DOMINATION_ENGINE — Daily task generation trigger
-- REAL INTEGRATION: /src/lib/db/seo-domination-queries.ts
-- PHASE: 3

-- PLACEHOLDER: DATAFORSEO — Q&A seed data population
-- REAL INTEGRATION: /src/lib/integrations/dataforseo.ts
-- PHASE: 3
